---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: apoci
gitea_urls:
  api: https://git.erwanleboucher.dev/api/v1
  download: https://git.erwanleboucher.dev

before:
  hooks:
    - go mod tidy

builds:
  - id: apoci
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/apoci
    binary: apoci

archives:
  - id: apoci
    ids:
      - apoci
