package config

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func writeConfig(t *testing.T, content string) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "apoci.yaml")
	require.NoError(t, os.WriteFile(path, []byte(content), 0o600))
	return path
}

func TestLoadMinimalConfig(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
`, dir))

	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, "https://test.example.com", cfg.Endpoint)
	require.Equal(t, "test.example.com", cfg.Domain)
	require.Equal(t, "test.example.com", cfg.Name)
}

func TestLoadFullConfig(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://registry.example.com"
name: "my-registry"
listen: ":8080"
dataDir: %q
keyPath: "/tmp/ap.key"
logLevel: debug
logFormat: text
region: eu-west
`, dir))

	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, "my-registry", cfg.Name)
	require.Equal(t, ":8080", cfg.Listen)
	require.Equal(t, dir, cfg.DataDir)
	require.Equal(t, "debug", cfg.LogLevel)
	require.Equal(t, "eu-west", cfg.Region)
}

func TestDefaults(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
`, dir))

	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, ":5000", cfg.Listen)
	require.Equal(t, dir, cfg.DataDir)
	require.Equal(t, "info", cfg.LogLevel)
	require.Equal(t, "json", cfg.LogFormat)
	require.NotEmpty(t, cfg.RegistryToken, "token should be auto-generated")
}

func TestMissingEndpoint(t *testing.T) {
	path := writeConfig(t, `
name: "test"
`)
	_, err := Load(path)
	require.Error(t, err, "expected error for missing endpoint")
}

func TestInvalidLogLevel(t *testing.T) {
	path := writeConfig(t, `
endpoint: "https://test.example.com"
logLevel: verbose
`)
	_, err := Load(path)
	require.Error(t, err, "expected error for invalid log level")
}

func TestFileNotFound(t *testing.T) {
	_, err := Load("/nonexistent/path/apoci.yaml")
	require.Error(t, err, "expected error for missing file")
}

func TestLimitsDefaults(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
`, dir))
	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, DefaultMaxManifestSize, cfg.Limits.MaxManifestSize)
	require.Equal(t, DefaultMaxBlobSize, cfg.Limits.MaxBlobSize)
}

func TestRegistryTokenAutoGenerated(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
`, dir))

	cfg, err := Load(path)
	require.NoError(t, err)
	require.NotEmpty(t, cfg.RegistryToken, "token should be auto-generated")
	require.Len(t, cfg.RegistryToken, 64, "token should be 32 bytes hex-encoded")

	// Second load should return the same token.
	cfg2, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, cfg.RegistryToken, cfg2.RegistryToken, "token should be stable across loads")
}

func TestRegistryTokenExplicit(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
registryToken: "my-secret-token"
`, dir))

	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, "my-secret-token", cfg.RegistryToken)
}

func TestAccountDomainDefault(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://registry.example.com"
dataDir: %q
`, dir))
	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, "registry.example.com", cfg.AccountDomain)
}

func TestAccountDomainExplicit(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://registry.example.com"
dataDir: %q
accountDomain: "example.com"
`, dir))
	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, "example.com", cfg.AccountDomain)
	require.Equal(t, "registry.example.com", cfg.Domain)
}

func TestAccountDomainRejectsScheme(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://registry.example.com"
dataDir: %q
accountDomain: "https://example.com"
`, dir))
	_, err := Load(path)
	require.Error(t, err)
	require.Contains(t, err.Error(), "bare hostname")
}

func TestAccountDomainRejectsPort(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://registry.example.com"
dataDir: %q
accountDomain: "example.com:8080"
`, dir))
	_, err := Load(path)
	require.Error(t, err)
	require.Contains(t, err.Error(), "bare hostname")
}

func TestLimitsCustomValues(t *testing.T) {
	dir := t.TempDir()
	path := writeConfig(t, fmt.Sprintf(`
endpoint: "https://test.example.com"
dataDir: %q
limits:
  maxManifestSize: 5242880
  maxBlobSize: 1073741824
`, dir))
	cfg, err := Load(path)
	require.NoError(t, err)
	require.Equal(t, int64(5242880), cfg.Limits.MaxManifestSize)
	require.Equal(t, int64(1073741824), cfg.Limits.MaxBlobSize)
}
